version: '3.1'
services:
  api:
    image: adamcaron/flip-api:dev
    ports:
     - 8085:8085
    volumes:
     - ${API_MOUNT}:/api
    entrypoint: node_modules/.bin/nodemon
    command:
     - -L
     - server.js
  ui:
    image: adamcaron/flip-ui:dev
    ports:
     - 8080:8080
    volumes:
     - ${UI_MOUNT}:/ui
    working_dir: /ui
    entrypoint: node
    command:
     - build/dev-server.js