version: '3.1'
services:
  api:
    image: adamcaron/flip:dev
    ports:
     - 8085:8085
    volumes:
     - ${API_MOUNT}:/api
    entrypoint: node_modules/.bin/nodemon
    command:
     - -L
     - server.js
  ui:
    image: node:alpine
    ports:
     - 8080:8080
    volumes:
     - ${UI_MOUNT}:/ui
    working_dir: /ui
    entrypoint: sh
    command:
     - -c
     - |
       npm install
       exec node build/dev-server.js