version: '3.1'
services:
  api:
    image: localhost/flip-api:dev
    volumes:
      - ${API_MOUNT}:/api/src
    entrypoint: node_modules/.bin/nodemon
    command:
      - -L
      - src/server.js
    networks:
      - swarmtools_proxy
    deploy:
      labels:
        - "traefik.port=8085"
        - "traefik.frontend.rule=PathPrefix:/api/"
  ui:
    image: localhost/flip-ui:dev
    volumes:
      - ${UI_MOUNT}:/ui/src
    working_dir: /ui
    entrypoint: node
    command:
      - build/dev-server.js
    networks:
      - swarmtools_proxy
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=PathPrefix:/"
networks:
  swarmtools_proxy:
    external: true

