version: '3.1'
services:
  proxy: # swarm-wide proxy
    image: traefik
    ports:
      - "80:80"
      - "8080:8080" # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --web
      - --docker
      - --docker.swarmmode
      - --logLevel=DEBUG
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.role == manager
  registry:
    image: registry
    volumes:
      - /local/registry_data:/var/lib/registry
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.port=5000"
        - "traefik.frontend.rule=PathPrefix:/v2/"
networks:
  proxy:

